modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "bedracket"
version = "${version}"
displayName = "BedRacket"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.bedracket]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bedracket]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "bedracket.mixins.json"
